CREATE TABLE Users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(256) NOT NULL,
    pwHash VARCHAR(256) NOT NULL,
    signupDate DATETIME NOT NULL DEFAULT NOW(),
    isAdmin BOOLEAN NOT NULL
);

CREATE TABLE Posts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(32) NOT NULL,
    body TEXT NOT NULL,
    sightingDate DATETIME NOT NULL,
    sightingLoc VARCHAR(64),
    postDate DATETIME NOT NULL DEFAULT NOW(),
    posterID INT NOT NULL,
    FOREIGN KEY (posterID) REFERENCES Users(id)
);

CREATE TABLE PostImages (
    id INT PRIMARY KEY AUTO_INCREMENT,
    postID INT NOT NULL,
    FOREIGN KEY (postID) REFERENCES Posts(id),
    imgPath VARCHAR(128) NOT NULL
);

CREATE TABLE Comments(
    id INT PRIMARY KEY AUTO_INCREMENT,
    body VARCHAR(256) NOT NULL,
    postID INT NOT NULL,
    FOREIGN KEY (postID) REFERENCES Posts(id),
    posterID INT NOT NULL,
    FOREIGN KEY (posterID) REFERENCES Users(id),
    commentDate TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE News(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(64) NOT NULL,
    link VARCHAR(256) NOT NULL,
    newsDate DATETIME NOT NULL DEFAULT NOW()
);
